# Climate Visibility Intelligence Dashboard

## Notebook 02 - Data Cleaning

### Objective

Clean the raw weather dataset before feature engineering and model building.

Tasks:

- Convert date column
- Handle missing values
- Remove unnecessary features
- Fix invalid values
- Save cleaned dataset

In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/weatherHistory.csv")

In [2]:
df_clean = df.copy()

In [3]:
df_clean.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [5]:
df_clean["Formatted Date"] = pd.to_datetime(
    df_clean["Formatted Date"],
    utc=True
)

In [6]:
df_clean["Formatted Date"].dtype

datetime64[us, UTC]

In [7]:
print("Start Date :", df_clean["Formatted Date"].min())
print("End Date   :", df_clean["Formatted Date"].max())

Start Date : 2005-12-31 23:00:00+00:00
End Date   : 2016-12-31 22:00:00+00:00

In [8]:
df["Loud Cover"].value_counts()

Loud Cover
0.0    96453
Name: count, dtype: int64

In [9]:
df_clean["Loud Cover"].nunique()

1

In [10]:
df_clean.drop(columns=["Loud Cover"], inplace=True)

In [11]:
df_clean.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Pressure (millibars)',
       'Daily Summary'],
      dtype='str')

In [12]:
df_clean.shape

(96453, 11)

In [13]:
df_clean.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [14]:
df_clean[df_clean["Precip Type"].isnull()].head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary
52672,2012-04-11 14:00:00+00:00,Mostly Cloudy,NaN,19.016667,19.016667,0.26,14.8764,163.0,9.982,1002.40,Mostly cloudy until night.
52674,2012-04-11 16:00:00+00:00,Mostly Cloudy,NaN,17.850000,17.850000,0.28,13.7977,169.0,9.982,1001.79,Mostly cloudy until night.
52675,2012-04-11 17:00:00+00:00,Mostly Cloudy,NaN,16.322222,16.322222,0.32,10.8192,151.0,9.982,1001.60,Mostly cloudy until night.
52677,2012-04-11 19:00:00+00:00,Mostly Cloudy,NaN,12.566667,12.566667,0.43,9.0160,159.0,9.982,1001.92,Mostly cloudy until night.
52678,2012-04-11 20:00:00+00:00,Mostly Cloudy,NaN,12.927778,12.927778,0.47,17.6295,197.0,16.100,1002.20,Mostly cloudy until night.

In [15]:
missing_percentage = (
    df_clean["Precip Type"].isnull().sum()
    / len(df_clean)
) * 100

print(f"Missing Percentage: {missing_percentage:.2f}%")

Missing Percentage: 0.54%

In [19]:
df_clean["Precip Type"].value_counts(dropna=False)

Precip Type
rain    85224
snow    10712
NaN       517
Name: count, dtype: int64

In [20]:
df_clean.dropna(subset=["Precip Type"], inplace=True)

In [21]:
df_clean.isnull().sum()

Formatted Date              0
Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Pressure (millibars)        0
Daily Summary               0
dtype: int64

In [22]:
df_clean.shape

(95936, 11)

In [23]:
df_clean.duplicated().sum()

np.int64(24)

In [24]:
df_clean.drop_duplicates(inplace=True)

In [25]:
df_clean.duplicated().sum()

np.int64(0)

In [26]:
df_clean.shape

(95912, 11)

In [27]:
df_clean.to_csv(
    "../data/processed/weatherHistory_cleaned.csv",
    index=False
)

# Notebook 02 Completed

### Tasks Completed

- Data type conversion
- DateTime standardization (UTC)
- Removed zero variance feature
- Handled missing values
- Removed duplicate rows
- Saved cleaned dataset

---

### Output File

```text
data/processed/weatherHistory_cleaned.csv
```

---

### Next Notebook

**Notebook 03 - Exploratory Data Analysis (EDA)**

In the next notebook, we will explore the cleaned dataset using visualizations and statistical analysis to understand relationships between weather features and visibility.