# Climate Visibility Intelligence Dashboard

# Notebook 04 - Feature Engineering

## Objective

Prepare the cleaned dataset for machine learning by creating useful features and transforming variables.

### Author
Tanmoy Das

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/weatherHistory.csv")

In [3]:
df_feature = df.copy()

In [4]:
df_feature.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [5]:
df_feature["Formatted Date"] = pd.to_datetime(
    df_feature["Formatted Date"],
    utc=True
)

In [6]:
df_feature["Formatted Date"].dtype

datetime64[us, UTC]

In [7]:
df_feature["Year"] = df_feature["Formatted Date"].dt.year
df_feature["Month"] = df_feature["Formatted Date"].dt.month
df_feature["Day"] = df_feature["Formatted Date"].dt.day
df_feature["Hour"] = df_feature["Formatted Date"].dt.hour
df_feature["DayOfWeek"] = df_feature["Formatted Date"].dt.dayofweek

In [8]:
df_feature[["Formatted Date","Year","Month","Day","Hour","DayOfWeek"]].head()

             Formatted Date  Year  Month  Day  Hour  DayOfWeek
0 2006-03-31 22:00:00+00:00  2006      3   31    22          4
1 2006-03-31 23:00:00+00:00  2006      3   31    23          4
2 2006-04-01 00:00:00+00:00  2006      4    1     0          5
3 2006-04-01 01:00:00+00:00  2006      4    1     1          5
4 2006-04-01 02:00:00+00:00  2006      4    1     2          5

In [9]:
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"

In [10]:
df_feature["Season"] = df_feature["Month"].apply(get_season)

In [14]:
df_feature[["Month", "Season"]].head(10)

   Month  Season
0      3  Spring
1      3  Spring
2      4  Spring
3      4  Spring
4      4  Spring
5      4  Spring
6      4  Spring
7      4  Spring
8      4  Spring
9      4  Spring

In [15]:
df_feature["Season"].value_counts()

Season
Summer    24309
Spring    24288
Autumn    24024
Winter    23832
Name: count, dtype: int64

In [16]:
df_feature["IsWeekend"] = df_feature["DayOfWeek"].apply(
    lambda x: 1 if x >= 5 else 0
)

In [17]:
df_feature[
    ["DayOfWeek", "IsWeekend"]
].head(15)

    DayOfWeek  IsWeekend
0           4          0
1           4          0
2           5          1
3           5          1
4           5          1
5           5          1
6           5          1
7           5          1
8           5          1
9           5          1
10          5          1
11          5          1
12          5          1
13          5          1
14          5          1

In [18]:
df_feature["IsWeekend"].value_counts()

IsWeekend
0    68901
1    27552
Name: count, dtype: int64

In [20]:
df_feature.select_dtypes(include="str").columns

Index(['Summary', 'Precip Type', 'Daily Summary', 'Season'], dtype='str')

In [22]:
for col in df_feature.select_dtypes(include="str").columns:
    print(f"{col}: {df_feature[col].nunique()} unique values")

Summary: 27 unique values
Precip Type: 2 unique values
Daily Summary: 214 unique values
Season: 4 unique values

In [23]:
df_feature = df_feature.drop(columns=["Daily Summary"])

In [25]:
df_feature.select_dtypes(include="str").columns

Index(['Summary', 'Precip Type', 'Season'], dtype='str')

In [27]:
for col in df_feature.select_dtypes(include="str").columns:
    print(f"{col}: {df_feature[col].nunique()} unique values")

Summary: 27 unique values
Precip Type: 2 unique values
Season: 4 unique values

In [ ]:
df_feature = pd.get_dummies(
    df_feature,
    columns=["Summary", "Precip Type", "Season"],
    dtype=int
)

In [36]:
df_feature.head()

,Formatted Date,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Year,...,Summary_Windy and Foggy,Summary_Windy and Mostly Cloudy,Summary_Windy and Overcast,Summary_Windy and Partly Cloudy,Precip Type_rain,Precip Type_snow,Season_Autumn,Season_Spring,Season_Summer,Season_Winter
0,2006-03-31 22:00:00+00:00,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,2006,...,0,0,0,0,1,0,0,1,0,0
1,2006-03-31 23:00:00+00:00,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,2006,...,0,0,0,0,1,0,0,1,0,0
2,2006-04-01 00:00:00+00:00,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,2006,...,0,0,0,0,1,0,0,1,0,0
3,2006-04-01 01:00:00+00:00,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,2006,...,0,0,0,0,1,0,0,1,0,0
4,2006-04-01 02:00:00+00:00,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,2006,...,0,0,0,0,1,0,0,1,0,0

In [30]:
df_feature.shape

(96453, 48)

In [39]:
df_feature.drop(columns=["Formatted Date"], inplace=True)

In [40]:
df_feature.to_csv(
    "../data/processed/weather_feature_engineered.csv",
    index=False
)

In [38]:
import os

os.path.exists("../data/processed/weather_feature_engineered.csv")

True

# Notebook 04 Summary

### Tasks Completed

- Extracted Year, Month, Day, Hour, and Day of Week from the datetime column.
- Created Season and IsWeekend features.
- Removed the unnecessary Daily Summary text column.
- Applied One-Hot Encoding to Summary, Precip Type, and Season.
- Prepared the dataset for machine learning models.
- Saved the processed dataset to the data/processed folder.

### Output File

weather_feature_engineered.csv